/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class AAMayus0 extends PMayus0
{
    private TMayus _mayus_;

    public AAMayus0()
    {
        // Constructor
    }

    public AAMayus0(
        @SuppressWarnings("hiding") TMayus _mayus_)
    {
        // Constructor
        setMayus(_mayus_);

    }

    @Override
    public Object clone()
    {
        return new AAMayus0(
            cloneNode(this._mayus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAMayus0(this);
    }

    public TMayus getMayus()
    {
        return this._mayus_;
    }

    public void setMayus(TMayus node)
    {
        if(this._mayus_ != null)
        {
            this._mayus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mayus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mayus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mayus_ == child)
        {
            this._mayus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mayus_ == oldChild)
        {
            setMayus((TMayus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
