/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class AAP0 extends PP0
{
    private PP1 _p1_;

    public AAP0()
    {
        // Constructor
    }

    public AAP0(
        @SuppressWarnings("hiding") PP1 _p1_)
    {
        // Constructor
        setP1(_p1_);

    }

    @Override
    public Object clone()
    {
        return new AAP0(
            cloneNode(this._p1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAP0(this);
    }

    public PP1 getP1()
    {
        return this._p1_;
    }

    public void setP1(PP1 node)
    {
        if(this._p1_ != null)
        {
            this._p1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._p1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._p1_ == child)
        {
            this._p1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._p1_ == oldChild)
        {
            setP1((PP1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
