/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class AASp extends PSp
{
    private PSp0 _sp0_;

    public AASp()
    {
        // Constructor
    }

    public AASp(
        @SuppressWarnings("hiding") PSp0 _sp0_)
    {
        // Constructor
        setSp0(_sp0_);

    }

    @Override
    public Object clone()
    {
        return new AASp(
            cloneNode(this._sp0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAASp(this);
    }

    public PSp0 getSp0()
    {
        return this._sp0_;
    }

    public void setSp0(PSp0 node)
    {
        if(this._sp0_ != null)
        {
            this._sp0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sp0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sp0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sp0_ == child)
        {
            this._sp0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sp0_ == oldChild)
        {
            setSp0((PSp0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
