/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class ACircleFig0 extends PFig0
{
    private TCircle _circle_;

    public ACircleFig0()
    {
        // Constructor
    }

    public ACircleFig0(
        @SuppressWarnings("hiding") TCircle _circle_)
    {
        // Constructor
        setCircle(_circle_);

    }

    @Override
    public Object clone()
    {
        return new ACircleFig0(
            cloneNode(this._circle_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACircleFig0(this);
    }

    public TCircle getCircle()
    {
        return this._circle_;
    }

    public void setCircle(TCircle node)
    {
        if(this._circle_ != null)
        {
            this._circle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._circle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._circle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._circle_ == child)
        {
            this._circle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._circle_ == oldChild)
        {
            setCircle((TCircle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
