/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class TCircle extends Token
{
    public TCircle()
    {
        super.setText("circle");
    }

    public TCircle(int line, int pos)
    {
        super.setText("circle");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCircle(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCircle(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCircle text.");
    }
}
