/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class TFill extends Token
{
    public TFill()
    {
        super.setText("fill");
    }

    public TFill(int line, int pos)
    {
        super.setText("fill");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFill(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFill(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFill text.");
    }
}
