/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class TRx extends Token
{
    public TRx()
    {
        super.setText("rx");
    }

    public TRx(int line, int pos)
    {
        super.setText("rx");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRx(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRx(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRx text.");
    }
}
