/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class TSvg2 extends Token
{
    public TSvg2()
    {
        super.setText("</svg>");
    }

    public TSvg2(int line, int pos)
    {
        super.setText("</svg>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSvg2(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSvg2(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSvg2 text.");
    }
}
