/* This file was generated by SableCC (http://www.sablecc.org/). */

package svg.node;

import svg.analysis.*;

@SuppressWarnings("nls")
public final class TWidth extends Token
{
    public TWidth()
    {
        super.setText("width");
    }

    public TWidth(int line, int pos)
    {
        super.setText("width");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWidth(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWidth(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWidth text.");
    }
}
