/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AAF extends PF
{
    private PD _d_;

    public AAF()
    {
        // Constructor
    }

    public AAF(
        @SuppressWarnings("hiding") PD _d_)
    {
        // Constructor
        setD(_d_);

    }

    @Override
    public Object clone()
    {
        return new AAF(
            cloneNode(this._d_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAF(this);
    }

    public PD getD()
    {
        return this._d_;
    }

    public void setD(PD node)
    {
        if(this._d_ != null)
        {
            this._d_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._d_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._d_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._d_ == child)
        {
            this._d_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._d_ == oldChild)
        {
            setD((PD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
