/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AAFi extends PFi
{
    private TFill _fill_;
    private TIg _ig_;
    private TC0 _c0_;

    public AAFi()
    {
        // Constructor
    }

    public AAFi(
        @SuppressWarnings("hiding") TFill _fill_,
        @SuppressWarnings("hiding") TIg _ig_,
        @SuppressWarnings("hiding") TC0 _c0_)
    {
        // Constructor
        setFill(_fill_);

        setIg(_ig_);

        setC0(_c0_);

    }

    @Override
    public Object clone()
    {
        return new AAFi(
            cloneNode(this._fill_),
            cloneNode(this._ig_),
            cloneNode(this._c0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAFi(this);
    }

    public TFill getFill()
    {
        return this._fill_;
    }

    public void setFill(TFill node)
    {
        if(this._fill_ != null)
        {
            this._fill_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fill_ = node;
    }

    public TIg getIg()
    {
        return this._ig_;
    }

    public void setIg(TIg node)
    {
        if(this._ig_ != null)
        {
            this._ig_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ig_ = node;
    }

    public TC0 getC0()
    {
        return this._c0_;
    }

    public void setC0(TC0 node)
    {
        if(this._c0_ != null)
        {
            this._c0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fill_)
            + toString(this._ig_)
            + toString(this._c0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fill_ == child)
        {
            this._fill_ = null;
            return;
        }

        if(this._ig_ == child)
        {
            this._ig_ = null;
            return;
        }

        if(this._c0_ == child)
        {
            this._c0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fill_ == oldChild)
        {
            setFill((TFill) newChild);
            return;
        }

        if(this._ig_ == oldChild)
        {
            setIg((TIg) newChild);
            return;
        }

        if(this._c0_ == oldChild)
        {
            setC0((TC0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
