/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AAS extends PS
{
    private PSp1 _sp1_;

    public AAS()
    {
        // Constructor
    }

    public AAS(
        @SuppressWarnings("hiding") PSp1 _sp1_)
    {
        // Constructor
        setSp1(_sp1_);

    }

    @Override
    public Object clone()
    {
        return new AAS(
            cloneNode(this._sp1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAS(this);
    }

    public PSp1 getSp1()
    {
        return this._sp1_;
    }

    public void setSp1(PSp1 node)
    {
        if(this._sp1_ != null)
        {
            this._sp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sp1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sp1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sp1_ == child)
        {
            this._sp1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sp1_ == oldChild)
        {
            setSp1((PSp1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
