/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABF extends PF
{
    private PD _d_;
    private PAtt _att_;

    public ABF()
    {
        // Constructor
    }

    public ABF(
        @SuppressWarnings("hiding") PD _d_,
        @SuppressWarnings("hiding") PAtt _att_)
    {
        // Constructor
        setD(_d_);

        setAtt(_att_);

    }

    @Override
    public Object clone()
    {
        return new ABF(
            cloneNode(this._d_),
            cloneNode(this._att_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABF(this);
    }

    public PD getD()
    {
        return this._d_;
    }

    public void setD(PD node)
    {
        if(this._d_ != null)
        {
            this._d_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._d_ = node;
    }

    public PAtt getAtt()
    {
        return this._att_;
    }

    public void setAtt(PAtt node)
    {
        if(this._att_ != null)
        {
            this._att_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._att_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._d_)
            + toString(this._att_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._d_ == child)
        {
            this._d_ = null;
            return;
        }

        if(this._att_ == child)
        {
            this._att_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._d_ == oldChild)
        {
            setD((PD) newChild);
            return;
        }

        if(this._att_ == oldChild)
        {
            setAtt((PAtt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
