/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABP extends PP
{
    private PP3 _p3_;
    private PAtt _att_;

    public ABP()
    {
        // Constructor
    }

    public ABP(
        @SuppressWarnings("hiding") PP3 _p3_,
        @SuppressWarnings("hiding") PAtt _att_)
    {
        // Constructor
        setP3(_p3_);

        setAtt(_att_);

    }

    @Override
    public Object clone()
    {
        return new ABP(
            cloneNode(this._p3_),
            cloneNode(this._att_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABP(this);
    }

    public PP3 getP3()
    {
        return this._p3_;
    }

    public void setP3(PP3 node)
    {
        if(this._p3_ != null)
        {
            this._p3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p3_ = node;
    }

    public PAtt getAtt()
    {
        return this._att_;
    }

    public void setAtt(PAtt node)
    {
        if(this._att_ != null)
        {
            this._att_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._att_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._p3_)
            + toString(this._att_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._p3_ == child)
        {
            this._p3_ = null;
            return;
        }

        if(this._att_ == child)
        {
            this._att_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._p3_ == oldChild)
        {
            setP3((PP3) newChild);
            return;
        }

        if(this._att_ == oldChild)
        {
            setAtt((PAtt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
