/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABPr extends PPr
{
    private PPr _pr_;
    private PPr1 _pr1_;

    public ABPr()
    {
        // Constructor
    }

    public ABPr(
        @SuppressWarnings("hiding") PPr _pr_,
        @SuppressWarnings("hiding") PPr1 _pr1_)
    {
        // Constructor
        setPr(_pr_);

        setPr1(_pr1_);

    }

    @Override
    public Object clone()
    {
        return new ABPr(
            cloneNode(this._pr_),
            cloneNode(this._pr1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABPr(this);
    }

    public PPr getPr()
    {
        return this._pr_;
    }

    public void setPr(PPr node)
    {
        if(this._pr_ != null)
        {
            this._pr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pr_ = node;
    }

    public PPr1 getPr1()
    {
        return this._pr1_;
    }

    public void setPr1(PPr1 node)
    {
        if(this._pr1_ != null)
        {
            this._pr1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pr1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pr_)
            + toString(this._pr1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pr_ == child)
        {
            this._pr_ = null;
            return;
        }

        if(this._pr1_ == child)
        {
            this._pr1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pr_ == oldChild)
        {
            setPr((PPr) newChild);
            return;
        }

        if(this._pr1_ == oldChild)
        {
            setPr1((PPr1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
