/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ABSp1 extends PSp1
{
    private PSp1 _sp1_;
    private PSp3 _sp3_;

    public ABSp1()
    {
        // Constructor
    }

    public ABSp1(
        @SuppressWarnings("hiding") PSp1 _sp1_,
        @SuppressWarnings("hiding") PSp3 _sp3_)
    {
        // Constructor
        setSp1(_sp1_);

        setSp3(_sp3_);

    }

    @Override
    public Object clone()
    {
        return new ABSp1(
            cloneNode(this._sp1_),
            cloneNode(this._sp3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABSp1(this);
    }

    public PSp1 getSp1()
    {
        return this._sp1_;
    }

    public void setSp1(PSp1 node)
    {
        if(this._sp1_ != null)
        {
            this._sp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sp1_ = node;
    }

    public PSp3 getSp3()
    {
        return this._sp3_;
    }

    public void setSp3(PSp3 node)
    {
        if(this._sp3_ != null)
        {
            this._sp3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sp3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sp1_)
            + toString(this._sp3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sp1_ == child)
        {
            this._sp1_ = null;
            return;
        }

        if(this._sp3_ == child)
        {
            this._sp3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sp1_ == oldChild)
        {
            setSp1((PSp1) newChild);
            return;
        }

        if(this._sp3_ == oldChild)
        {
            setSp3((PSp3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
