/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACC1 extends PC1
{
    private PAtt _att_;
    private PC2 _c2_;
    private PAtt _a_;

    public ACC1()
    {
        // Constructor
    }

    public ACC1(
        @SuppressWarnings("hiding") PAtt _att_,
        @SuppressWarnings("hiding") PC2 _c2_,
        @SuppressWarnings("hiding") PAtt _a_)
    {
        // Constructor
        setAtt(_att_);

        setC2(_c2_);

        setA(_a_);

    }

    @Override
    public Object clone()
    {
        return new ACC1(
            cloneNode(this._att_),
            cloneNode(this._c2_),
            cloneNode(this._a_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACC1(this);
    }

    public PAtt getAtt()
    {
        return this._att_;
    }

    public void setAtt(PAtt node)
    {
        if(this._att_ != null)
        {
            this._att_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._att_ = node;
    }

    public PC2 getC2()
    {
        return this._c2_;
    }

    public void setC2(PC2 node)
    {
        if(this._c2_ != null)
        {
            this._c2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c2_ = node;
    }

    public PAtt getA()
    {
        return this._a_;
    }

    public void setA(PAtt node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._att_)
            + toString(this._c2_)
            + toString(this._a_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._att_ == child)
        {
            this._att_ = null;
            return;
        }

        if(this._c2_ == child)
        {
            this._c2_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._att_ == oldChild)
        {
            setAtt((PAtt) newChild);
            return;
        }

        if(this._c2_ == oldChild)
        {
            setC2((PC2) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((PAtt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
