/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AConcatenarFiguraExp extends PExp
{
    private PExp _exp_;
    private PPr1 _pr1_;

    public AConcatenarFiguraExp()
    {
        // Constructor
    }

    public AConcatenarFiguraExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PPr1 _pr1_)
    {
        // Constructor
        setExp(_exp_);

        setPr1(_pr1_);

    }

    @Override
    public Object clone()
    {
        return new AConcatenarFiguraExp(
            cloneNode(this._exp_),
            cloneNode(this._pr1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcatenarFiguraExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PPr1 getPr1()
    {
        return this._pr1_;
    }

    public void setPr1(PPr1 node)
    {
        if(this._pr1_ != null)
        {
            this._pr1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pr1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._pr1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._pr1_ == child)
        {
            this._pr1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._pr1_ == oldChild)
        {
            setPr1((PPr1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
