/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACPr extends PPr
{
    private PPr _pr_;
    private PFig1 _fig1_;

    public ACPr()
    {
        // Constructor
    }

    public ACPr(
        @SuppressWarnings("hiding") PPr _pr_,
        @SuppressWarnings("hiding") PFig1 _fig1_)
    {
        // Constructor
        setPr(_pr_);

        setFig1(_fig1_);

    }

    @Override
    public Object clone()
    {
        return new ACPr(
            cloneNode(this._pr_),
            cloneNode(this._fig1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACPr(this);
    }

    public PPr getPr()
    {
        return this._pr_;
    }

    public void setPr(PPr node)
    {
        if(this._pr_ != null)
        {
            this._pr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pr_ = node;
    }

    public PFig1 getFig1()
    {
        return this._fig1_;
    }

    public void setFig1(PFig1 node)
    {
        if(this._fig1_ != null)
        {
            this._fig1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fig1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pr_)
            + toString(this._fig1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pr_ == child)
        {
            this._pr_ = null;
            return;
        }

        if(this._fig1_ == child)
        {
            this._fig1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pr_ == oldChild)
        {
            setPr((PPr) newChild);
            return;
        }

        if(this._fig1_ == oldChild)
        {
            setFig1((PFig1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
