/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACPr extends PPr
{
    private PPr1 _pr1_;
    private TMinus _minus_;
    private TSl _sl_;
    private PFg _fg_;
    private TMayus _mayus_;

    public ACPr()
    {
        // Constructor
    }

    public ACPr(
        @SuppressWarnings("hiding") PPr1 _pr1_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") TSl _sl_,
        @SuppressWarnings("hiding") PFg _fg_,
        @SuppressWarnings("hiding") TMayus _mayus_)
    {
        // Constructor
        setPr1(_pr1_);

        setMinus(_minus_);

        setSl(_sl_);

        setFg(_fg_);

        setMayus(_mayus_);

    }

    @Override
    public Object clone()
    {
        return new ACPr(
            cloneNode(this._pr1_),
            cloneNode(this._minus_),
            cloneNode(this._sl_),
            cloneNode(this._fg_),
            cloneNode(this._mayus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACPr(this);
    }

    public PPr1 getPr1()
    {
        return this._pr1_;
    }

    public void setPr1(PPr1 node)
    {
        if(this._pr1_ != null)
        {
            this._pr1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pr1_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public TSl getSl()
    {
        return this._sl_;
    }

    public void setSl(TSl node)
    {
        if(this._sl_ != null)
        {
            this._sl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sl_ = node;
    }

    public PFg getFg()
    {
        return this._fg_;
    }

    public void setFg(PFg node)
    {
        if(this._fg_ != null)
        {
            this._fg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fg_ = node;
    }

    public TMayus getMayus()
    {
        return this._mayus_;
    }

    public void setMayus(TMayus node)
    {
        if(this._mayus_ != null)
        {
            this._mayus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mayus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pr1_)
            + toString(this._minus_)
            + toString(this._sl_)
            + toString(this._fg_)
            + toString(this._mayus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pr1_ == child)
        {
            this._pr1_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._sl_ == child)
        {
            this._sl_ = null;
            return;
        }

        if(this._fg_ == child)
        {
            this._fg_ = null;
            return;
        }

        if(this._mayus_ == child)
        {
            this._mayus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pr1_ == oldChild)
        {
            setPr1((PPr1) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._sl_ == oldChild)
        {
            setSl((TSl) newChild);
            return;
        }

        if(this._fg_ == oldChild)
        {
            setFg((PFg) newChild);
            return;
        }

        if(this._mayus_ == oldChild)
        {
            setMayus((TMayus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
