/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADC1 extends PC1
{
    private PC2 _c2_;

    public ADC1()
    {
        // Constructor
    }

    public ADC1(
        @SuppressWarnings("hiding") PC2 _c2_)
    {
        // Constructor
        setC2(_c2_);

    }

    @Override
    public Object clone()
    {
        return new ADC1(
            cloneNode(this._c2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADC1(this);
    }

    public PC2 getC2()
    {
        return this._c2_;
    }

    public void setC2(PC2 node)
    {
        if(this._c2_ != null)
        {
            this._c2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._c2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._c2_ == child)
        {
            this._c2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._c2_ == oldChild)
        {
            setC2((PC2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
