/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADF extends PF
{
    private PAtt _att_;
    private PD _d_;
    private PAtt _a_;

    public ADF()
    {
        // Constructor
    }

    public ADF(
        @SuppressWarnings("hiding") PAtt _att_,
        @SuppressWarnings("hiding") PD _d_,
        @SuppressWarnings("hiding") PAtt _a_)
    {
        // Constructor
        setAtt(_att_);

        setD(_d_);

        setA(_a_);

    }

    @Override
    public Object clone()
    {
        return new ADF(
            cloneNode(this._att_),
            cloneNode(this._d_),
            cloneNode(this._a_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADF(this);
    }

    public PAtt getAtt()
    {
        return this._att_;
    }

    public void setAtt(PAtt node)
    {
        if(this._att_ != null)
        {
            this._att_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._att_ = node;
    }

    public PD getD()
    {
        return this._d_;
    }

    public void setD(PD node)
    {
        if(this._d_ != null)
        {
            this._d_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._d_ = node;
    }

    public PAtt getA()
    {
        return this._a_;
    }

    public void setA(PAtt node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._att_)
            + toString(this._d_)
            + toString(this._a_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._att_ == child)
        {
            this._att_ = null;
            return;
        }

        if(this._d_ == child)
        {
            this._d_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._att_ == oldChild)
        {
            setAtt((PAtt) newChild);
            return;
        }

        if(this._d_ == oldChild)
        {
            setD((PD) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((PAtt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
