/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADNombreFigura extends PNombreFigura
{
    private TEllipse _ellipse_;

    public ADNombreFigura()
    {
        // Constructor
    }

    public ADNombreFigura(
        @SuppressWarnings("hiding") TEllipse _ellipse_)
    {
        // Constructor
        setEllipse(_ellipse_);

    }

    @Override
    public Object clone()
    {
        return new ADNombreFigura(
            cloneNode(this._ellipse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADNombreFigura(this);
    }

    public TEllipse getEllipse()
    {
        return this._ellipse_;
    }

    public void setEllipse(TEllipse node)
    {
        if(this._ellipse_ != null)
        {
            this._ellipse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ellipse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ellipse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ellipse_ == child)
        {
            this._ellipse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ellipse_ == oldChild)
        {
            setEllipse((TEllipse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
