/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADP extends PP
{
    private PP3 _p3_;

    public ADP()
    {
        // Constructor
    }

    public ADP(
        @SuppressWarnings("hiding") PP3 _p3_)
    {
        // Constructor
        setP3(_p3_);

    }

    @Override
    public Object clone()
    {
        return new ADP(
            cloneNode(this._p3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADP(this);
    }

    public PP3 getP3()
    {
        return this._p3_;
    }

    public void setP3(PP3 node)
    {
        if(this._p3_ != null)
        {
            this._p3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._p3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._p3_ == child)
        {
            this._p3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._p3_ == oldChild)
        {
            setP3((PP3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
