/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AFFig0 extends PFig0
{
    private TPolyline _polyline_;

    public AFFig0()
    {
        // Constructor
    }

    public AFFig0(
        @SuppressWarnings("hiding") TPolyline _polyline_)
    {
        // Constructor
        setPolyline(_polyline_);

    }

    @Override
    public Object clone()
    {
        return new AFFig0(
            cloneNode(this._polyline_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFFig0(this);
    }

    public TPolyline getPolyline()
    {
        return this._polyline_;
    }

    public void setPolyline(TPolyline node)
    {
        if(this._polyline_ != null)
        {
            this._polyline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._polyline_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._polyline_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._polyline_ == child)
        {
            this._polyline_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._polyline_ == oldChild)
        {
            setPolyline((TPolyline) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
