/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TPerro extends Token
{
    public TPerro()
    {
        super.setText("perro");
    }

    public TPerro(int line, int pos)
    {
        super.setText("perro");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPerro(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPerro(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPerro text.");
    }
}
