/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TPolygon extends Token
{
    public TPolygon()
    {
        super.setText("polygon");
    }

    public TPolygon(int line, int pos)
    {
        super.setText("polygon");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPolygon(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPolygon(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPolygon text.");
    }
}
