/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TT extends Token
{
    public TT()
    {
        super.setText("tortuga");
    }

    public TT(int line, int pos)
    {
        super.setText("tortuga");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TT(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTT(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TT text.");
    }
}
