/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TX0 extends Token
{
    public TX0()
    {
        super.setText("x");
    }

    public TX0(int line, int pos)
    {
        super.setText("x");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TX0(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTX0(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TX0 text.");
    }
}
