/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TX1 extends Token
{
    public TX1()
    {
        super.setText("x1");
    }

    public TX1(int line, int pos)
    {
        super.setText("x1");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TX1(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTX1(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TX1 text.");
    }
}
